### ISSUE TITLE
Unable to select country when purchasing

### ISSUE THREAD

**Issue by fromkeith** [printdotio/pio.js#113] opened 2017-11-14 17:22 UTC
# What is happening
I am unable to change (or even select) the country I want to ship my purchase to.

# What should happen
The country should be selectable/changable.

# Repo Steps
1. Enable a product that ships everywhere/Global. Eg. Accessory pouches.
2. To prevent any caching, open widget page in an Incognito window.
3. Add Accessory pouches.
4. Checkout until the Shipping Address
5. Country is greyed out, and unclickable

# Impact
Customers cannot purchase Gifts as they cannot specify their country.
Revenue and sales are lost.

# Tested on
Chrome 63
Firefox 59
Edge 38

**Comment by micahasmith** [comment] 2017-11-14 21:33
country selection happens in the top left menu in the widget, or via setting it in the widget config. It defaults to the IP-based lookup of the users country. 

since the selection of products available is a product of the ship to country, country selection must come first.

**Comment by micahasmith** [comment] 2017-11-14 21:34
closing as functionality is as intended

**Closed as completed by micahasmith** 2017-11-14 21:34 UTC

**Comment by fromkeith** [comment] 2017-11-14 21:37
> It defaults to the IP-based lookup of the users country.

I'm in Canada. When I use chrome it defaults to Canada. When I used Firefox and Edge it defaulted to the US. This does not reflect what you just specified.
Furthermore, a customer in New Zealand had their country default to the US.

I seem to remember an older version of this widget that would preemptively popup a country selector before someone could purchase. Did that get removed?

**Comment by fromkeith** [comment] 2017-11-15 17:41
I turned on my VPN and did some testing.
Below are the results.

Country => The country selected as the exit VPN IP
GeoIp => Using https://geoiptool.com/ to determine the "country" of my IP
Gooten => What your widget shows on checkout.

## Chrome
```
    Country,GeoIp,Gooten
    Australia,Australia,United States (scottsdale Arizona)
    New Zealand,New Zealand,New Zealand (auckland auk)
    United Kingdom, United Kingdom, United Kingdom
```

## Firefox
```
    Country,GeoIp,Gooten
    Australia, Australia, United States (scottsdale Arizona)
    New Zealand,New Zealand, United States (Alabama)
    United Kingdom, United Kingdom,United States (Alabama)
```

As you can see your application is _not_ working as intended.

**Comment by fromkeith** [comment] 2017-11-17 20:39
Any update or questions about the VPN test?

**Comment by micahasmith** [comment] 2017-11-17 20:41
did you clear local cache and local storage in between tests?

**Comment by fromkeith** [comment] 2017-11-17 20:43
New "Private Browser/Incognito" window each time.

1. Set VPN to country
1. Open Incognito
2. Check GeoIP
3. Check Gooten
4. Close Incognito window
5. Repeat

**Comment by fromkeith** [comment] 2017-11-23 20:02
Any update on re-opening this ticket?
